apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      env: sandbox
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name: nginx
        image: krishnakant888/nginx
        ports:
        - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  selector:
    matchLabels:
      env: sandbox2
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        env: sandbox2
    spec:
      containers:
      - name: nginx2
        image: krishnakant888/nginx2
        ports:
        - containerPort: 80
