apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    env: sandbox2
spec:
  selector:
    matchLabels:
      env: sandbox
  replicas: 6 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name: nginx
        image: krishnakant888/nginx
        ports:
        - containerPort: 80
