apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /kk
          backend:
            serviceName: nginx-service
            servicePort: 5678
        - path: /pk
          backend:
            serviceName: example-service
            servicePort: 5678
